### ISSUE TITLE
different behavior in different python3 version

### ISSUE THREAD

**Issue by Trim21** [asottile/pyupgrade#214]
I'm using `pyupgrade` in my project, and I run `pre-commit run --all-files` on my CircleCI with multi python version including `3.6`, `3.7`, and `3.8`.

(And I'm developing under python3.7)

But I found it only fails only in `3.8.0` with hook `pyupgrade` .

```yaml
repos:
  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        require_serial: true
        language: python
        types: [python]
        args: ['--py36-plus']
```

(I manager my `pyupgrade` version with package manager and its `1.25.0`)

```diff
 def print_version():
-    return '''BGmi %sver. %s%s built by %sRicterZ%s with ❤️
+    return '''BGmi {}ver. {}{} built by {}RicterZ{} with ❤️

 Github: https://github.com/BGmi/BGmi
 Email: ricterzheng@gmail.com
-Blog: https://ricterz.me''' % (YELLOW, __version__, COLOR_END, YELLOW, COLOR_END)
+Blog: https://ricterz.me'''.format(YELLOW, __version__, COLOR_END, YELLOW, COLOR_END)
```
