### ISSUE TITLE
Add --check flag

### ISSUE THREAD

**Issue by saroad2** [asottile/pyupgrade#310]
I would like to use this tool not only as a formatting tool, but also as a checker in my CI/CD process, making sure that people use the latest APIs in their code.

In order to achieve that I would like to add a `--check` flag that cause the following behavior:
1. If no changes are needed in the given sources, return 0 exit code
2. If changes are needed **do not make those changes**, but only return error exit code.

**Comment by hugovk** [comment]
It would be useful but I expect this will be closed as a duplicate of https://github.com/asottile/pyupgrade/issues/210, so here's a workaround:

```sh
pyupgrade *.py --py36-plus  # or however you run it
test $(git status --porcelain | wc -l) = 0
```

If changes are needed, it _will_ actually make those changes (shouldn't matter too much on CI). And assuming your code is in Git, and nothing else has modified it, the second line will return 1 and fail the CI if changes were made. Otherwise it returns 0.

---

Alternatively, use it as part of pre-commit with something like this in `.pre-commit-config.yaml`:

```yml
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.4.3
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
```

And then run this on the CI:

```sh
pip install pre-commit
pre-commit run all-files
```
