### ISSUE TITLE
Incorrectly changing the typing annotation for dataclass

### ISSUE THREAD

**Issue by LER0ever** [asottile/pyupgrade#605]
pyupgrade currently gives incorrect corrections to dataclass decorated class, making all Typing annotations to lowercase. I'm not sure if it's because I aliased the class decorator (for dataclass-json) or it's a bug / oversight of pyupgrade not able to handle dataclass typing. 

```python
from dataclasses import dataclass
from dataclasses_json import dataclass_json

# wrap decorator so that I don't have to write two decorators for every class
def dc_json(cls):
    return dataclass_json(dataclass(cls))

@dc_json
class DCSource:
    id: int
    name: str
    pos: List[int]
```

Running with pre-commit, which calls pyupgrade 2.31.0 with the following arguments:

```bash
poetry run pyupgrade --keep-runtime-typing --py39-plus
```

All the typing annotations such as `Dict` and `List` will be changed to lowercase, which would result in incorrect dataclass generation.

```diff
diff --git a/ebony/data.py b/ebony/data.py
index f9b4171..b57aa30 100644
--- a/ebony/data.py
+++ b/ebony/data.py
@@ -14,7 +14,7 @@ def dc_json(cls):
 class DCSource:
     id: int
     name: str
-    pos: List[int]
+    pos: list[int]
```

**Comment by asottile** [comment]
"incorrect dataclass generation"? what does that mean?

**Comment by asottile** [comment]
works fine for me:

```console
$ python3 t.py 
{"id": 1, "name": "foo", "pos": [1, 2, 3]}
$ cat t.py 
from dataclasses import dataclass
from dataclasses_json import dataclass_json

# wrap decorator so that I don't have to write two decorators for every class
def dc_json(cls):
    return dataclass_json(dataclass(cls))

@dc_json
class DCSource:
    id: int
    name: str
    pos: list[int]

print(DCSource(1, 'foo', [1, 2, 3]).to_json())
```

I suspect you're running on something older than python3.9, in which case you obviously shouldn't use `--py39-plus`

**Comment by LER0ever** [comment]
> I suspect you're running on something older than python3.9

Oops... I did run pre-commit hooks inside a python 3.8 virtualenv. It works as expected after switching to Python 3.9. Sorry for the confusion @asottile

**Comment by asottile** [comment]
a tip for next time, **show what you're seeing** -- so I don't have to guess at what you think the bug is and what the fix should be

and if you're confused / want a reference I've put together a video that helps you frame questions: https://youtu.be/ritp4gAqNMI

**Comment by LER0ever** [comment]
> a tip for next time, show what you're seeing -- so I don't have to guess at what you think the bug is and what the fix should be

@asottile Sure thing. I initially thought it was an obvious missing feature (support for dataclass). That's why I did not file the issue like a bug report and attach the reproduction steps. Turns out it was a mistake on my end. 

And for future reference in case someone also encounter similar issues. I did the following in my pre-commit-config.yaml:

```yaml
default_language_version:
  python: python3.8

default_stages: [commit, push]

exclude: 'third_party|paper|rosenbridge|exp|tmp|venv|.git'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --keep-runtime-typing --py39-plus
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [python]
        language: system

...
```

Changing the arguments for pyupgrade to `--py38-plus` solves the problem. 

And it's actually a weird behavior from pre-commit. Running the exact command with `--py39-plus` even under a Python 3.8 venv will not touch those typing definitions, but running pyupgrade through the pre-commit configuration above changes all `List` to lowercase. 🤔
