### ISSUE TITLE
add inline ignore comment

### ISSUE THREAD

**Issue by Cielquan** [asottile/pyupgrade#622]
I have a py3.10 code base and run pyupgrade via pre-commit.

In this code base I use pydantic models which use
> standard library typing types as defined in PEP 484 to define complex objects.

[link to docs](https://pydantic-docs.helpmanual.io/usage/types/#typing-iterables)

So I have to define a model like this (example from docs):
```python
from typing import List

from pydantic import BaseModel


class Model(BaseModel):
    simple_list: list = None
    list_of_ints: List[int] = None
```

Which in turn gets modified by pyupgrade:
```diff
class Model(BaseModel):
    simple_list: list = None
-    list_of_ints: List[int] = None
+    list_of_ints: list[int] = None
```

And this results in a `RuntimeError` from pydantic.

To prevent this I currently use the workaround of skiping the model files whole which I luckily have in their own subpackage by ignoring them via the pre-commit config. But skiping them whole is a strong solution and I would rather skip single lines with something like a `# noqa` comment of some sort.

**Comment by MarcoGorelli** [comment]
you can use [keep-runtime-typing](https://github.com/asottile/pyupgrade#pep-585-typing-rewrites)

**Comment by Cielquan** [comment]
The skip is only needed for the model classes. Other classes or functions would also be skipped with this flag then, right? I would have to give up on annotation upgrades for everything then, which I would like to avoid.

I unfortunately forgot while writing the OP that I also (will) have pydantic models outside of the models subpackage, which only holds DB models. The codebase is a fastAPI app. But the issue only occurred with the DB models till now. So even having 2 entries in pre-commit config (One for the model subpackage with the flag and one for the rest without it.) won't cut it unfortunately.

**Comment by Cielquan** [comment]
As a temporary better solution than full ignore I have this now:
```yaml
  - repo: https://github.com/asottile/pyupgrade
    rev: e695ecd365119ab4e5463f6e49bea5f4b7ca786b # frozen: v2.31.0
    hooks:
      - id: pyupgrade
        name: pyupgrade (not models)
        args: ["--py310-plus"]
        exclude: .*\/models\/.*
      - id: pyupgrade
        name: pyupgrade (models)
        args: ["--py310-plus", "--keep-runtime-typing"]
        files: .*\/models\/.*
```

Which in turn results in:
```
pre-commit run pyupgrade --all-files
pyupgrade (not models)...................................................Passed
pyupgrade (models).......................................................Failed
- hook id: pyupgrade
- exit code: 1
- files were modified by this hook

Rewriting packages/swlp-api/app/models/user/user.py
Rewriting packages/swlp-api/app/models/user/user_role.py
```

So the `--keep-runtime-typing` flag does not apply correctly? Or is my config not right?
