### ISSUE TITLE
Annotations are modified in py3.10 with `--keep-runtime-typing` set

### ISSUE THREAD

**Issue by Cielquan** [asottile/pyupgrade#623]
The bug still remains https://github.com/asottile/pyupgrade/issues/622#issuecomment-1088393650.

Unfortunately you were wrong, when you suggested, that the used python version may be lower then 3.10 while I specify >=3.10 is supported. Would have probably been easier to fix then.

The venv (called py_env-python3.10) inside the .cache/pre-commit/repo... directory is using python 3.10 and it still changes the annotations while `--keep-runtime-typing` is set.

- pyupgrade version: 2.31.1
- `python = "^3.10"` is set in package metadata (using poetry)
- pre-commit version: 2.18.1
- OS: win 10
- Installed python versions: 3.6, 3.7, 3.8, 3.9, 3.10
- Default python version: 3.10 (highest in PATH and chosen when run `python` or `py` in terminal)
- I run pre-commit via tox (config below) with 3.10 set
- I ran `pre-commit clean` and retried

### .pre-commit-config.yaml
```yaml
---
minimum_pre_commit_version: "2.16"
default_stages: [commit]
default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: e695ecd365119ab4e5463f6e49bea5f4b7ca786b # frozen: v2.31.0
    hooks:
      - id: pyupgrade
        name: pyupgrade (not models)
        args: ["--py310-plus"]
        exclude: .*\/models\/.*
        language_version: python3.10
      - id: pyupgrade
        name: pyupgrade (models)
        args: ["--py310-plus", "--keep-runtime-typing"]
        files: .*\/models\/.*
        language_version: python3.10
```

### tox.ini
```ini
[tox]
package = dev

minversion = 3.15.0
skip_missing_interpreters = true
isolated_build = true
skipsdist = true
envlist = pre-commit-run


[testenv]
description = call any pre-commit command e.g.: `tox -e pre-commit -- autoupdate --freeze`
basepython = python3.10
envdir = {toxworkdir}/pre-commit
passenv =
    HOME
    CI
    SSH_AUTH_SOCK
    SKIP
setenv =
    PIP_DISABLE_VERSION_CHECK = 1
    SKIP = {tty:identity:},{env:SKIP:}
download = true
skip_install = true
deps = pre-commit >= 2.17
commands = pre-commit {posargs}


[testenv:pre-commit-run]
description = run all or given pre-commit hooks (e.g. in CI)
commands = pre-commit run {posargs} --all-files {tty::--show-diff-on-failure} {tty:--color always:}
```

### Commandline output
```
$ tox -e pre-commit-run -- pyupgrade                                                                                                                                              
pre-commit-run installed: cfgv==3.3.1,distlib==0.3.4,filelock==3.6.0,identify==2.4.12,nodeenv==1.6.0,platformdirs==2.5.1,pre-commit==2.18.1,PyYAML==6.0,six==1.16.0,toml==0.10.2,virtualenv==20.14.0
pre-commit-run run-test-pre: PYTHONHASHSEED='711'
pre-commit-run run-test: commands[0] | pre-commit run pyupgrade --all-files --color always
pyupgrade (not models)...................................................Passed
pyupgrade (models).......................................................Failed
- hook id: pyupgrade
- exit code: 1
- files were modified by this hook

Rewriting packages/swlp-api/app/models/user/user.py
Rewriting packages/swlp-api/app/models/user/user_role.py

ERROR: InvocationError for command 'C:\Users\<user>\projects\swlp-main\.tox\pre-commit\Scripts\pre-commit.EXE' run pyupgrade --all-files --color always (exited with code 1)
____________________________________________________________________________________ summary ____________________________________________________________________________________ 
ERROR:   pre-commit-run: commands failed
```

### user.py diff
```diff
"""User database and data models."""
# pylint: disable=R0903
import typing

from sqlmodel import Field, Relationship, SQLModel

from . import UserRoleLink


if typing.TYPE_CHECKING:
    from . import UserRole, UserRoleRead

...

class User(_UserBase, table=True):
    """User database model."""

    __tablename__ = "users"

    id: int | None = Field(default=None, primary_key=True)  # noqa: VNE003

-    roles: typing.List["UserRole"] = Relationship(back_populates="users", link_model=UserRoleLink)
+    roles: list["UserRole"] = Relationship(back_populates="users", link_model=UserRoleLink)

...

class UserReadWithRoles(UserRead):
    """User data model for reading database entries with associated roles."""

-    roles: typing.List["UserRoleRead"] = []
+    roles: list["UserRoleRead"] = []

```

### user_role.py
Has the same case like user.py.

I hope you can help me here, because I cannot seem to find the issue.

EDIT: added pyupgrade version in use
