### ISSUE TITLE
"Union" is not replaced with "|" in user-defined type hints

### ISSUE THREAD

**Issue by AIGeneratedUsername** [asottile/pyupgrade#645]
### Sample code:
```python
from typing import Union

FooBar = Union[str, int]
```

### Current result:

No changes

### Expected result 

```python
FooBar = int | str
```

---

### pre-commit config:

```yaml
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
```

---

I've tried to search over open and closed issues, but I found nothing. If it is an expected behavior, then it will be nice to document this.
