### ISSUE TITLE
Newer type annotations not "found" in Python 3.8 

### ISSUE THREAD

**Issue by GitRon** [asottile/pyupgrade#824]
Hi @asottile !

First, thx for your great tool! It's amazing and I was looking for something like this for ages!

I maintain a package, which is supposed to be compatible with Pyhton 3.8-311.

Here is my `pre-commit` config:

````yml
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        args: [ --py38-plus ]
        language_version: python3.11
        stages: [ push ]
````

Here's a piece of code which is not compatible:

````python
def generate_default_permissions(model_name: str) -> list[str]:
    return [
        f'add_{model_name}',
        f'change_{model_name}',
        f'delete_{model_name}',
        f'view_{model_name}',
    ]

````

The type hint for the return value is not compatible but `pyupgrade` is not complaining.

Is this a bug or did I misconfigure something?

Thx!  
Ronny
