### ISSUE TITLE
--py3-plus: Remove unnecessary "# -*- coding: utf-8 -*-" cookie

### ISSUE THREAD

**Issue by jdufresne** [asottile/pyupgrade#89]
In Python 3, source files are decoded as utf-8 by default. This allows Python 3 only codebases to drop the encoding cookie, `# -*- coding: utf-8 -*-`. pyupgrade could include this transformation when `--py3-plus` is passed.

**Comment by asottile** [comment]
This is handled by [`fix-encoding-pragma` in pre-commit/pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks) -- for the behaviour you want you can use `args: [--remove]`

**Comment by a-t-0** [comment]
Is it possible to configure `pyupgrade` to allow the file encoding explicitly in python 3.8? I understand experienced programmers may be aware of the default encoding of python files, however, I would like it to be stated explicitly in the python files.

For the pragma, I use:
```
# Runs additional tests that are created by the pre-commit software itself.
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.2.0
   hooks:
    # Add <# -*- coding: utf-8 -*-> to the top of python files.
    - id: fix-encoding-pragma
```

And for pyupgrade, I use the following `.pre-commit-config.yaml`:
```
# Updates the syntax of `.py` files to the specified python version.
# It is not compatible with: pre-commit hook: fix-encoding-pragma
 - repo: https://github.com/asottile/pyupgrade
   rev: v2.32.1
   hooks:
     - id: pyupgrade
       args: [--py38-plus]
```
However, this results in `pragma` adding the encoding (as expected), and then `pyupgrade` removing the encodings again. I also tried omitting the `args: [--py38-plus]`. However, then `pyupgrade` still removes the encodings when running `pre-commit run --all-files`.
